### ISSUE TITLE
Gmail will NOT accept adding the extension

### ISSUE THREAD

**Issue by frafor** [jparise/gmail-fixed-font#9]
No matter how, the button to activate the extension was **never** in the condition that will move to active when clicked.

The extension was *actively* not allowed by Chrome.

As a matter of fact, Gmail should simply show messages that are sent only in text mode using monospace font. if the user does not like it, then can always change it.

**Comment by PepeSifontes** [comment]
Any news on this?

**Comment by PepeSifontes** [comment]
This  extension will do the job as well,  not sure if it is by the same developer:

https://chrome.google.com/webstore/detail/gmail-monospace-font/eghfgaofkemobknodgopcbonnglhbfhe

**Comment by jparise** [comment]
I'll try to have a look, but I've personally been using the [Stylish version of this recipe](https://github.com/jparise/gmail-fixed-font#stylish), and it's been working fine in recent Chrome versions.

**Comment by jparise** [comment]
It looks like Chrome no long supports running user scripts as extensions. You can only use extensions that come from the Chrome Web Store.

https://support.google.com/chrome_webstore/answer/2811969?visit_id=637281910861504368-1012785594&p=ui_remove_non_cws_extensions&hl=en&rd=2

I'll remove those installation instructions from the README.

The other ways to use this script are still valid, so please try one of them as an alternative. I don't plan to package this as a full Chrome Web Store extension because there are others already there that do the same thing, and I don't think having another would be additive at this point.
